# Generated by Django 5.2 on 2025-12-16 12:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Challenge name', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the challenge')),
                ('short_description', models.CharField(help_text='Brief summary for cards', max_length=150)),
                ('duration_days', models.PositiveIntegerField(help_text='Challenge duration in days')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('goal_type', models.CharField(choices=[('weight', 'Weight Loss'), ('fitness', 'Fitness & Strength'), ('mental_health', 'Mental Health'), ('nutrition', 'Nutrition & Diet'), ('sleep', 'Sleep Quality'), ('hydration', 'Hydration'), ('flexibility', 'Flexibility'), ('endurance', 'Endurance'), ('mindfulness', 'Mindfulness'), ('general', 'General Wellness')], default='general', max_length=20)),
                ('tracking_type', models.CharField(choices=[('boolean', 'Yes/No (Completed or Not)'), ('numeric', 'Numeric (e.g., steps, calories)'), ('time', 'Time-based (e.g., minutes)'), ('count', 'Count (e.g., glasses of water)')], default='boolean', max_length=20)),
                ('daily_target', models.DecimalField(blank=True, decimal_places=2, help_text='Daily target value (for numeric/time/count tracking)', max_digits=10, null=True)),
                ('daily_requirement', models.TextField(help_text='What users need to do daily (e.g., "Walk 10,000 steps")')),
                ('points_reward', models.PositiveIntegerField(default=100, help_text='Points earned on completion')),
                ('badge_name', models.CharField(blank=True, help_text='Badge name for completion', max_length=100)),
                ('badge_icon', models.CharField(blank=True, help_text='Emoji or icon for badge', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is challenge available to join?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage?')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Max users (optional)', null=True)),
                ('recommended_for_bmi_range', models.CharField(blank=True, help_text='e.g., "18.5-25" or "25-30"', max_length=50)),
                ('recommended_for_goals', models.JSONField(blank=True, default=list, help_text='List of wellness goals this suits')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='challenges/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days completed')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest streak achieved')),
                ('days_completed', models.PositiveIntegerField(default=0, help_text='Total days completed')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('badge_earned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about the challenge')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Challenge',
                'verbose_name_plural': 'User Challenges',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'challenge', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='ChallengeBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.userchallenge')),
            ],
            options={
                'verbose_name': 'Challenge Badge',
                'verbose_name_plural': 'Challenge Badges',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False, help_text='Did user complete the requirement?')),
                ('value_logged', models.DecimalField(blank=True, decimal_places=2, help_text='Actual value achieved (steps, minutes, etc.)', max_digits=10, null=True)),
                ('mood', models.CharField(blank=True, choices=[('excited', '😄 Excited'), ('motivated', '💪 Motivated'), ('normal', '😊 Normal'), ('tired', '😴 Tired'), ('struggling', '😓 Struggling')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('very_hard', 'Very Hard')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the day')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('user_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='challenges.userchallenge')),
            ],
            options={
                'verbose_name': 'Daily Check-In',
                'verbose_name_plural': 'Daily Check-Ins',
                'ordering': ['-date'],
                'unique_together': {('user_challenge', 'date')},
            },
        ),
    ]
