# Generated by Django 5.2 on 2025-12-16 15:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.PositiveIntegerField(default=2000, help_text='Daily calorie target')),
                ('protein_goal', models.PositiveIntegerField(default=50, help_text='Daily protein target (grams)')),
                ('carbs_goal', models.PositiveIntegerField(default=250, help_text='Daily carbs target (grams)')),
                ('fat_goal', models.PositiveIntegerField(default=70, help_text='Daily fat target (grams)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Goal',
                'verbose_name_plural': 'Nutrition Goals',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('food_name', models.CharField(help_text='Name or description of the food', max_length=200)),
                ('portion', models.CharField(help_text='e.g., 1 cup, 100g, 2 slices', max_length=100)),
                ('calories', models.PositiveIntegerField(help_text='Calories (kcal)')),
                ('protein', models.DecimalField(decimal_places=1, default=0, help_text='Protein in grams', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, default=0, help_text='Carbohydrates in grams', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=1, default=0, help_text='Fat in grams', max_digits=6)),
                ('meal_date', models.DateField(default=datetime.date.today)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['-meal_date', '-logged_at'],
                'indexes': [models.Index(fields=['user', 'meal_date'], name='nutrition_m_user_id_91c3ff_idx'), models.Index(fields=['meal_date'], name='nutrition_m_meal_da_1bbd68_idx')],
            },
        ),
    ]
