# Generated by Django 5.2 on 2025-12-16 15:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('calm', '😌 Calm'), ('neutral', '😐 Neutral'), ('sad', '😢 Sad'), ('stressed', '😰 Stressed'), ('anxious', '😟 Anxious'), ('energetic', '⚡ Energetic'), ('tired', '😴 Tired')], max_length=20)),
                ('note', models.TextField(blank=True, help_text="Optional: Add a short note about how you're feeling", null=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Entry',
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-entry_date', '-created_at'],
                'unique_together': {('user', 'entry_date')},
            },
        ),
    ]
